const int LMax=3;
const int S[LMax]={8, 8, 8};
const int Smax=512;
const int Pmax=21;
const int SingleTNum=LMax;
const int TotalTNum=Smax*LMax;
const int MaxInt=99999999;
const int Maskcode=0x000000ff;
const int RoundMax=1000;
const double Randa=0.5;
const int MaxExchangetime=100;
const int IPv4len=32;
unsigned int IPsegsz[IPv4len]={0};
const int MapLen=3;
const int Intbitlen=sizeof(int)*8;
const int EclassNum=1; // number of equivalent classes
const int EclassSID[EclassNum]={0}; //IDs of representative switches for each equivalent class  
const int CCencoding_enable=1;
